### ISSUE TITLE
VaultServer deployment fails on OpenShift due to wrong secret

### ISSUE THREAD

**Issue by s3lph** [kubevault/project#105]
### What are you trying to achieve?

Deploy VaultServer instances on OpenShift 4.

### What do you expect to happen?

When fetching the Service Account token, the Operator should fetch the correct secret.

### What is happening instead?

The KubeVault Operator fetches all secrets for the ServiceAccount and uses the first secret in the list without checking whether it indeed is a ServiceAccount token. See [pkg/util/util.go:46][src]:

```go
34	sa, err := kc.CoreV1().ServiceAccounts(namespace).Get(context.TODO(), name, metav1.GetOptions{})
//...
43		for _, s := range sa.Secrets {
44			sr, err := kc.CoreV1().Secrets(namespace).Get(context.TODO(), s.Name, metav1.GetOptions{})
45			if err == nil {
46				return sr, nil  // <----- Here the first secret is returned.
//...
```

This works on vanilla k8s, where the only secret attached to a ServiceAccount is a token. However, OpenShift also creates a dockercfg secret for each service account:

```yaml
$ oc get sa -n kubevault-vault -oyaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: vault
    cluster: vault
  name: vault
  namespace: kubevault-vault
  ownerReferences:
  - apiVersion: kubevault.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: VaultServer
    name: vault
    uid: c381f846-c778-11ea-8545-022227cc0c1e
imagePullSecrets:
- name: vault-dockercfg-nrj4h
secrets:
- name: vault-dockercfg-nrj4h  # <-- dockercfg listed first
- name: vault-token-xh8kv
```

Since there is no guarantee that the token secrets are listed first, the KubeVault Operator sometimes ends up with the dockercfg secret instead, and then fails to properly configure the VaultServer, since the chosen secret does not contain the key `token`.

As a potential fix, the code above should additionally check for `type == kubernetes.io/service-account-token` before returning the secret.

[src]: https://github.com/kubevault/operator/blob/3535586316cb243c4b4648fbacf06b148da73c0c/pkg/util/util.go#L33
