### ISSUE TITLE
VaultPolicy creation fails due to missing keys in policy

### ISSUE THREAD

**Issue by mhamann** [kubevault/project#106]
According to the [docs](https://kubevault.com/docs/v0.3.0/concepts/policy-crds/vaultpolicy/) for KubeVault v0.3.0, a VaultPolicy manifest could look something like this:

```
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: db-pxc
spec:
  vaultRef:
    name: vault
  policy:
    path:
      pxc-secret/*:
        capabilities:
        - create
        - read
        - update
        - delete
```

Attempting to apply that to a cluster where KubeVault is installed yields the following validation errors:

```
The VaultPolicy "db-pxc" is invalid: 
* spec.policy.apiVersion: Required value: must not be empty
* spec.policy.kind: Required value: must not be empty
```

I don't see those fields specified in the CRD, so I don't understand why this error is being returned.

I'm testing this on Kubernetes 1.17.11.
