### ISSUE TITLE
Generate SecretProviderClass using KubeVault CLI

### ISSUE THREAD

**Issue by sakiib** [kubevault/project#112]
- User should be able to generate `SecretProviderClass` to use the `Secrets Store CSI driver` using `KubeVault CLI`. 
For example: `$ kubectl-vault create secret-provider-class ...`
- Detailed manifest files can be found [here](https://github.com/kubevault/demo/tree/master/webinar-08-12-21/deploy) if needed.

---
Here's the complete step by step manual procedure and we want to automate the `Step 3`:

**Step 1:** Enable `SecretEngine` and Create `SecretEngineRole` 

- [DB Admin] Enable a new `SecretEngine`
```yaml
apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: ${db-name} 
  namespace: ${db-namespace}
spec:
  ...
  path: k8s.-.${db-ns}.${db-name}
```

- [DB Admin] Create a `SecretEngineRole` e.g. `ElasticsearchRole`
```yaml
apiVersion: engine.kubevault.com/v1alpha1
kind: ElasticsearchRole
metadata:
  name: ${db-name}-${db-role-name} # name provided by db admin
  namespace: ${db-namespace} # VALIDATE: secretEngine ref is always from the same namespace
spec:
  # mutator sets vaultRef and path from secretEngine
  secretEngine:
    name: ${secret-engine-name}
  vaultRef:
    name:
    namespace:
    # path: "your-database-path"
```

**Step 2:** Create `VaultPolicy` & bind it to a `ServiceAccount` using `VaultPolicyBinding`

- [DB Admin] Create `VaultPolicy` 
```yaml
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: ${db-name}-${db-role-name}-reader # = ${policy-name}
  namespace: ${db-namespace}
spec:
  ...
  policyDocument: |
    path "k8s.-.${db-ns}.${db-name}/creds/${db-name}-${db-role-name}" {
      capabilities = ["read"]
    }
```

- [User] Create `ServiceAccount`
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-user-account
  namespace: test
```

- [Vault Admin] Create `VaultPolicyBinding`
```yaml
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: es-reader-role
  namespace: demo
spec:
  ...
  policies:
    - ref: es-reader-policy
```

**Step 3:** Create `SecretProviderClass`

- [User] Create `SecretProviderClass`
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-provider
  namespace: test
spec:
  provider: vault 
  parameters:
    vaultAddress: "http://vault.demo:8200"
    roleName: "k8s.-.demo.es-reader-role"   
    objects: |
      - objectName: "es-username"
        secretPath: "your-database-path/creds/k8s.-.demo.es-superuser-role" 
        secretKey: "username"
      - objectName: "es-password"
        secretPath: "your-database-path/creds/k8s.-.demo.es-superuser-role"
        secretKey: "password"
```

**Step 4:** Create a `Pod` & mount 

- [User] Create a `Pod` and mount the dynamically generated Database credentials in it.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  namespace: test
spec:
  ...
  serviceAccountName: test-user-account
```

---
Information we may need to generate the `SecretProviderClass`: 
- `vault` namespace for generating `vaultAddress`
- `roleName` may be generated from `VaultPolicyBinding` name, e.g. `k8s.(clusterName or -).namespace.name`
- `objectName` may be kept same as the respective `secretKey`
- `secretPath` may be generated from SecretEngineRole `ElasticsearchRole` name, `path/creds/name`
