### ISSUE TITLE
Vault operator design review

### ISSUE THREAD

**Issue by tamalsaha** [kubevault/project#20]
Video Recording: https://drive.google.com/drive/folders/1JG0eDTgosKTsUe_UtGGGA5SsFMlRGGKK?usp=sharing

-------------------------

Vault CRD --->
  - provision Vault server pods, s/a
  - unseal
  - Vault Service
  - AppBinding

1. "default" s/a will NOT be the reviewer service account

Bounded Token ???

2. Create s/a for each VaultServer crd

-> system:auth-delegator
-> Secret Read only unsealer secret

```
$ vault auth enable kubernetes
$ vault write auth/kubernetes/config \
    token_reviewer_jwt="reviewer_service_account_jwt" \
    kubernetes_host=https://192.168.99.100:8443 \
    kubernetes_ca_cert=@ca.crt
```

InClusterConfig

config.Host : https://10.0.0.1:443 // apply AKS fix
config.CA: []byte{}

VautlServer CRD
```
spec:
  authMethods:
    - type: kubernetes
      path: kubernetes
      *serviceAccount: <serviceAccountName>
      *secretName: (secretType: kubernetes.io/service-account-token )
      *kubernetes_host
      *kubernetes_ca_cert
    - type: aws
      path: <>
      secretName: (secretType: kubevault.com/aws )
```

- Kubernetes
- AWS
+++++++++++++++++
- AliCloud
- Azure
- Google Cloud

- Initial config of AuthMethod by ???, Authmethod syncer ???
- What about removed auth methods (via PATCH-ing crd)? probably Remove

~~~~~~~~~~~~~~~~~~~~~~~~

PolicyBinding
spec:
  users:
    - different types of auth method




AppBinding
  parameters:
    useServiceAccount: true (secret not provided)


By Default, Vault operator will create AppBinding like above (uses s/a for auth)


~~~~~~~~~~~~~~~~~~~~~~~~

Policy + PolicyBinding Controller
  requires policy: {

  }
  account: {

  }

ServiceAccount

<vault-server-crd-name>-reviewer : Kubernetes auth token reviewer

<vault-server-crd-name>-unsealer : Read Secret for unealing (used to mount VaultServer pods)

<vault-server-crd-name>-policy-controller : for Policy & PolicyBinding controller

```
path "sys/policy/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
```

```
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: <vault-crd-name>
spec:
  clientConfig:
    service:
      name:
  parameters:
    apiVersion: kubevault.com/v1alpha1
    kind: VaultServerConfiguration
    usePodServiceAccountForCSIDriver: true
    policyControllerServiceAccountName: <vault-crd-name>-policy-controller
    dbManagerServiceAccountName: <vault-crd-name>-db-manager
    authPath: kubernetes
```
--------------------
```
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: <vault-crd-name>
spec:
  clientConfig:
    service:
      name:
  parameters:
    apiVersion: kubevault.com/v1alpha1
    kind: VaultServerConfiguration
    authPath: aws-iam
  secret:
    name:
```

Sequence for VaultServer
------------------------
1. create service accounts (inside vault-operator):
  - `<vault>-unsealer`
  - `<vault>-kubernetes-token-reviewer`
     create a Secret (injected JWT into unsealer sidecar)
     system:auth-delegator RBAC
  - `<vault>-policy-controller`
  - Create `<vault>-auth-controller` s/a, Policy & PolicyBinding

2. Run Vault Server pods with unsealer sidecar (inside vault-operator):

3. Inside unsealer sidecar:
- unseal
- Enable kubernetes auth
- configure policy-controller s/a
 args:
  - --policy-controller-service-account=<vault>-policy-controller

4. Vault operator waits for unsealed Vault pod (inside vault-operator)
 - status
 - Enable additional auth methods via auth controller (inside vault-operator)

5. Policy/Bindging Controller: apply policy and bindings (inside vault-operator)

-------------------------

# CSI Driver
-------------------------
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vault-kv-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: com.vault.csi.vaultdbs
parameters:
  ref: AppBinding
  secretEngine: KV # vault engine name
  secretName: my-secret # secret name on vault which you want get access
```

-------------------
PVC
Pod mount

pod: nginx
ServiceAccount: nginx

1. Vault kube-auth enabled
2. nginx s/a policy to read secretName

Policy: kv-reader
-------
# capability of get secret
path "kv/secretName" {
  capabilities = ["read"]
}

PolicyBinding
-------------
nginx s/a
kv-reader policy

1. StorageClass
2. PVC using StorageClass
3. Policy and PolicyBinding
4. Pod

# DB User Manager
-------------------------------------------------------------------------

<vault-server-crd-name>-db-manager : for KubeDB user manager

```
path "database/config/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "database/roles/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "database/creds/*" {
  capabilities = ["read"]
}
```
