### ISSUE TITLE
DB manager design review

### ISSUE THREAD

**Issue by nightfury1204** [kubevault/project#23]
Step 1: Vault AppBinding
```
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: vault-app
  namespace: default
spec:
  secret:
    name: vault-root-token # token secret
  clientConfig:
    url: http://192.168.99.100:30001
#    service:
#      name: vault
#      scheme: http
#      port: 8200
    insecureSkipTLSVerify: true
```

Step 2: mongo AppBinding
```
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: mongo-app
  namespace: default
spec:
  secret:
    name: mongo-user-cred # secret 
  clientConfig:
    service:
      name: mongo
      scheme: http
      port: 8200
    insecureSkipTLSVerify: true
  parameters:
    allowedRoles: "*"
---
apiVersion: v1
data:
  username: 
  password: 
  connection_url:  // not required
kind: Secret
metadata:
  name: mongo-user-cred
  namespace: default
````
Step 3: Mongo db role
```
apiVersion: authorization.kubedb.com/v1alpha1
kind: MongoDBRole
metadata:
  name: test
spec:
  creationStatements:
    - "{ \"db\": \"admin\", \"roles\": [{ \"role\": \"readWrite\" }, {\"role\": \"read\", \"db\": \"foo\"}] }"
  dbName: mongo // delete
  defaultTTL: 300s
  maxTTL: 24h
  authManagerRef:
    type: vault
    namespace: default
    name: vault-app
  databaseRef:
    name: mongo-app
```
Step 4:
```
apiVersion: authorization.kubedb.com/v1alpha1
kind: MongoDBRoleBinding
metadata:
  name: test
spec:
  roleRef: test
  subjects:
    - kind: ServiceAccount
      name: mdb-rolebinding-sa
      namespace: default
  store:
    secret: mdb-credential
```

Role controller:
 - enable the database secrets engine if it is not already enabled
 - create database config for Mongodb
 - create role

Role Binding controller:
 - get credential store secret.
 - if lease id exists in secret, then check is it expired
 - get database credential, add lease info in status 

-----------------------------------------------
- namespace based name for role and rolebinding
  /database/role/k8s.-.ns.name
  /database/creds/k8s.-.ns.name
----------------------------------------

--------------------------------------------------
- databse config name

set name from databaseRef:
 databaseRef:
    namespace: default
    name: mongo-app\

name format: k8s.-.ns.name

-------------------------------------------------------

-------------------------------------------------------
```
apiVersion: authorization.kubedb.com/v1alpha1
kind: MongoDBRoleBinding
metadata:
  name: test
spec:
  roleRef: test
  subjects:
    - kind: ServiceAccount
      name: mdb-rolebinding-sa
      namespace: default
  store:
    secret: mdb-credential
```

// once access is approved or denied, object immutable
// using validator validation
```
apiVersion: authorization.kubedb.com/v1alpha1
kind: DatabaseAccessRequest
metadata:
  name: test
spec:
  TTL: 
  roleRef:
    kind: MongoDBROle
    name: 
    namespace:
  subjects:
    - kind: ServiceAccount
      name: mdb-rolebinding-sa
      namespace: default
Status:
  secret:
    name: metadate.Name.randomsuffix # credential secret

type DatabaseAccessgRequestStatus struct {
	// Conditions applied to the request, such as approval or denial.
	// +optional
	Conditions []CertificateSigningRequestCondition `json:"conditions,omitempty" protobuf:"bytes,1,rep,name=conditions"`

	// local object reference
	secret:
       name: metadate.Name.randomsuffix # credential secret
}

type RequestConditionType string

// These are the possible conditions for a certificate request.
const (
	AccessApproved RequestConditionType = "Approved"
	AccessDenied   RequestConditionType = "Denied"
)

type DatabaseAccessRequestCondition struct {
	// request approval state, currently Approved or Denied.
	Type RequestConditionType `json:"type" protobuf:"bytes,1,opt,name=type,casttype=RequestConditionType"`
	// brief reason for the request state
	// +optional
	Reason string `json:"reason,omitempty" protobuf:"bytes,2,opt,name=reason"`
	// human readable message with details about the request state
	// +optional
	Message string `json:"message,omitempty" protobuf:"bytes,3,opt,name=message"`
	// timestamp for the last update to this condition
	// +optional
	LastUpdateTime metav1.Time `json:"lastUpdateTime,omitempty" protobuf:"bytes,4,opt,name=lastUpdateTime"`
}
```
----------------------------------------------------------

---------------------------------------------------------------
database connection url from AppBinding

Give error if user give hard coded username, password in url

(url: "mongodb://{{username}}:{{password}}@mongo.default.svc:27017/admin?ssl=false") may contain hard coded 

 username

 password

--------------------
